"""add x and y

Revision ID: 09a775d42859
Revises: 21dec2e7ff3b
Create Date: 2025-03-29 23:14:02.881629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a775d42859'
down_revision: Union[str, None] = '21dec2e7ff3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spots', sa.Column('x_coordinate', sa.Float(), nullable=False))
    op.add_column('parking_spots', sa.Column('y_coordinate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_spots', 'y_coordinate')
    op.drop_column('parking_spots', 'x_coordinate')
    # ### end Alembic commands ###
