"""new table

Revision ID: 21dec2e7ff3b
Revises: cb6dbb1403f8
Create Date: 2025-03-29 20:36:52.231054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21dec2e7ff3b'
down_revision: Union[str, None] = 'cb6dbb1403f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_permissions', sa.Column('is_accepted', sa.Boolean(), nullable=True))
    op.add_column('parking_spots', sa.Column('parking_id', sa.Integer(), nullable=True))
    op.add_column('parking_spots', sa.Column('current_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parking_spots', 'users', ['current_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'parking_spots', 'parking_config', ['parking_id'], ['id'])
    op.drop_column('parking_spots', 'y_coordinate')
    op.drop_column('parking_spots', 'x_coordinate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spots', sa.Column('x_coordinate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('parking_spots', sa.Column('y_coordinate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'parking_spots', type_='foreignkey')
    op.drop_constraint(None, 'parking_spots', type_='foreignkey')
    op.drop_column('parking_spots', 'current_user_id')
    op.drop_column('parking_spots', 'parking_id')
    op.drop_column('access_permissions', 'is_accepted')
    # ### end Alembic commands ###
